use_frameworks!

platform :ios, '14.0'

target 'DocUATelemed_Example' do
  pod 'QuickBlox', '~> 2.17'
  pod 'Quickblox-WebRTC', '~> 2.8'
  pod 'ChatLayout', '~> 1.2'
  pod 'SnapKit', '~> 5.6'
  pod 'Kingfisher', '~> 7.3'
  pod 'DifferenceKit', '~> 1.3'
  pod 'InputBarAccessoryView', '~> 5.5'
  pod 'DocUATelemed', :path => '../'

  target 'DocUATelemed_Tests' do
    inherit! :search_paths

    
  end
end
